### ISSUE TITLE
iax2  "No best format in (codec2)???" error

### ISSUE THREAD

**Issue by evgenyh** [traud/asterisk-codec2#2]
on call attempt asterisk throws this error when only codec2 is allowed

 ERROR[23023]: chan_iax2.c:11350 socket_process_helper: No best format in (codec2)???

**Comment by traud** [comment]
Not tested myself because I do not use IAX2, but did you add Codec 2 to `iax2_format_compatibility_best(.)` as well?

**Comment by evgenyh** [comment]
> iax2_format_compatibility_best(.) as well?

nope. unsure what should I do there. will check later

**Comment by traud** [comment]
Based on your original patch, I thought about that, see first hunk): [iax2.patch.txt](https://github.com/traud/asterisk-codec2/files/837794/iax2.patch.txt)

**Comment by evgenyh** [comment]
I'll check this a bit later
have you tried this ?

**Comment by traud** [comment]
No, I have not tried because I am not using IAX2 – I do not have a second sever to talk to. It was just an idea to start from.

**Comment by evgenyh** [comment]
ok. I'll try soon and report back here.
btw, if you willing to be albe to test this as well I can provide you with access to another asterisk server, we are using for our lab.

**Comment by evgenyh** [comment]
works :) thank you

**Comment by traud** [comment]
Great and thanks for the feedback! I am closing this and we discuss the addition of IAX2 in your other issue report. If you face this issue again, please, do not hesitate to re-open this report. Furthermore, if you face other or different issue, please, do not hesitate to create new issue reports.
